KARMA_COST_NEW_TOPIC = 10
KARMA_COST_NEW_LINK = 1

MAX_CHANGE_PER_VOTE = 10

DEFAULT_PROFILE_KARMA = 20
CREATORS_KARMA_PER_VOTE = 1
DAMP_FACTOR = 1.1
DAMPEN_POINTS_AFTER = 1
TOP_TOPICS_ON_MAINPAGE = 1
NEW_TOPICS_ON_MAINPAGE = 1
DATE_FORMAT = '%Y-%m-%d'