KARMA_COST_NEW_TOPIC = 10
KARMA_COST_NEW_LINK = 1

MAX_CHANGE_PER_VOTE = 10

DEFAULT_PROFILE_KARMA = 20
CREATORS_KARMA_PER_VOTE = 1
DAMP_FACTOR = 1.1
DAMPEN_POINTS_AFTER = 100
TOP_TOPICS_ON_MAINPAGE = 3
NEW_TOPICS_ON_MAINPAGE = 3
DATE_FORMAT = '%Y-%m-%d'

CALCULATE_RELATED_AFTER = [10, 20, 50]
MAX_RELATED_LINKS = 10
MIN_VOTES_IN_RELATED = 5

LINKS_PER_PAGE = 15

#For Stats Page
TOP_TOPICS = 10
TOP_USERS = 10
TOP_LINKS = 10


#Recommnded for users